### ISSUE TITLE
incus copy fails inside a container

### ISSUE THREAD

**Issue by antifob** [zabbly/incus#13]
Hi,

When running `incus copy` inside an incus container, a segfault occurs. I don't know if it's a packaging issue or an incus issue. Feel free to redirect upstream.

## Steps to reproduce

```
incus launch images:debian/bookworm ctn
# in container "ctn"
# ... install incus
incus launch images:debian/bookworm a
incus copy a b
Error: Create instance from copy: Failed to run: rsync -a -HA --sparse --devices --delete --checksum --numeric-ids --xattrs --filter=-x security.selinux -q /var/lib/incus/storage-pools/default/containers/a/ /var/lib/incus/storage-pools/default/containers/b: signal: segmentation fault
```

## ctn config

```
$ incus config show --expanded ctn
architecture: x86_64
config:
  environment.HISTFILE: /dev/null
  image.architecture: amd64
  image.description: Debian bookworm amd64 (20231201_05:24)
  image.os: Debian
  image.release: bookworm
  image.serial: "20231201_05:24"
  image.type: squashfs
  image.variant: default
  security.guestapi: "false"
  security.idmap.isolated: "true"
  security.nesting: "true"
  security.privileged: "false"
  volatile.base_image: b283e6f3e32a1dce09d9e1a9bc40a79feeca25ba9b8c359f917b54b386eff487
  volatile.cloud-init.instance-id: 2a45ef79-8012-41a2-99ee-bfeecb26e957
  volatile.eth0.host_name: veth1af69aad
  volatile.eth0.hwaddr: 00:16:3e:3e:4e:52
  volatile.idmap.base: "1214112"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1214112,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1214112,"Nsid":0,"Maprange":65536}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1214112,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1214112,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 6f670ee7-f626-4bd7-8bcd-65a8d383aa47
  volatile.uuid.generation: 6f670ee7-f626-4bd7-8bcd-65a8d383aa47
devices:
  eth0:
    name: eth0
    network: incusbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

## a config

```
root@ctn:~# incus config show --expanded a
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Debian bullseye amd64 (20231201_05:24)
  image.os: Debian
  image.release: bullseye
  image.serial: "20231201_05:24"
  image.type: squashfs
  image.variant: default
  security.privileged: "true"
  volatile.base_image: 18451affa3476fe43dca17c016029dc6c426643e62a51d79fffe0f5cec4a5183
  volatile.cloud-init.instance-id: 76d0651f-ff9b-4c28-b58d-78249597c914
  volatile.eth0.host_name: vethcd21c6cb
  volatile.eth0.hwaddr: 00:16:3e:f3:2d:0f
  volatile.idmap.base: "0"
  volatile.idmap.current: '[]'
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 48b1335a-b6f9-425a-8b40-f483352527d7
  volatile.uuid.generation: 48b1335a-b6f9-425a-8b40-f483352527d7
devices:
  eth0:
    name: eth0
    network: incusbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

Thanks :)
