### ISSUE TITLE
Could a proxy not work, although it is shown...?

### ISSUE THREAD

**Issue by RudiOnTheAir** [zabbly/incus#58]
Hi

I`m running sftpgo on an incus container for a year without problems. But now i have a trouble with the PASV from unsecure ftp.
The filezilla client can connect normaly. But with wget i get the error message, the it cannot connect to 127.0.0.1:50002.
The script on a 2nd container goes via external domain name.

The settings of the sftpgo container:

----------------------------------------------------
```
incus config device show void-sftp 
eth0:
  ipv4.address: 10.217.37.85
  name: eth0
  network: incusbr0
  type: nic
ftp-2021to2021:
  connect: tcp:127.0.0.1:2021
  listen: tcp:0.0.0.0:2021
  type: proxy
ftp-50000-50100:
  connect: tcp:127.0.0.1:50000-50100
  listen: tcp:0.0.0.0:50000-50100
  type: proxy
sftp-2022to2022:
  connect: tcp:127.0.0.1:2022
  listen: tcp:0.0.0.0:2022
  type: proxy
```
--------------------------------------------------------
Only after changing the external domain to the internal 10.217.. ip it works again.

Don't understand what has happend... Any idea??

```
--2024-09-28 10:42:35--  ftp://files.domain.info:2021/RADIO/
           => '.listing'
Resolving files.domain.info... 2xx.1xx.160.12
Connecting to files.domain.info|2xx.1xx.160.12|:2021... connected.
Logging in as darc ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /RADIO ... done.
==> PASV ... couldn't connect to 127.0.0.1 port 50017: Connection refused
```
----------------------------------------------------------------------------
--
Tnx 

Wolf
