### ISSUE TITLE
incus admin init uses wrong interface 'eth0'

### ISSUE THREAD

**Issue by muellert** [zabbly/incus#71]
I just installed the latest stable package of 'incus' and initialized a cluster:

```
# incus admin init --dump
config:
  cluster.https_address: 10.1.0.3:8443
  core.https_address: 10.1.0.3:8443
networks:
- config:
    ipv4.address: 10.6.221.1/24
    ipv4.nat: "true"
    ipv6.address: fd42:994d:88fd:a44e::1/64
    ipv6.nat: "true"
  description: ""
  name: incusbr0
  type: bridge
  project: default
storage_pools:
- config:
    source: /var/lib/incus/storage-pools/default
    volatile.initial_source: /var/lib/incus/storage-pools/default
  description: ""
  name: default
  driver: btrfs
- config:
    source: /var/lib/incus/storage-pools/local
    volatile.initial_source: /var/lib/incus/storage-pools/local
  description: ""
  name: local
  driver: btrfs
storage_volumes: []
profiles:
- config: {}
  description: Default Incus profile
  devices:
    eth0:
      name: eth0
      network: incusbr0
      type: nic
    root:
      path: /
      pool: default
      type: disk
  name: default
projects:
- config:
    features.images: "true"
    features.networks: "true"
    features.networks.zones: "true"
    features.profiles: "true"
    features.storage.buckets: "true"
    features.storage.volumes: "true"
  description: Default Incus project
  name: default
```

Most modern Linux systems, I use Bookworm, do not have an `eth0`. It seems as if this config should be non-functional, or at least, there's also this error message after running the 'incus admin init' command:

```
Error: Failed to update profile "default": Device validation failed for "eth0": Cannot use "nictype" property in conjunction with "network" property
```

On my computer, the ethernet is only sometimes up, and it's called `enp2s0`.
