### ISSUE TITLE
Failed to run: forklimits=memlock:unlimited when trying to start VM

### ISSUE THREAD

**Issue by clendee** [zabbly/incus#82]
I recently upgraded to incus version 6.12 on Debian 12 on a small homelab setup.
The machine I'm running this on is ThinkCentre SFF M91p - 16GB RAM - 480GB SSD

Since upgrading to incus 6.12 (from 6.9), Im encountering the following error when trying to create or start a VM.

```
user@incsrv3:/run/incus$ inc start ha
Error: Failed to run: forklimits limit=memlock:unlimited:unlimited fd=3 fd=4 -- /opt/incus/bin/qemu-system-x86_64 -S -name ha -uuid b18afd29-194e-4d2a-ac26-d5f0a59ff691 -daemonize -cpu host,hv_passthrough -nographic -serial chardev:console -nodefaults -no-user-config -sandbox on,obsolete=deny,elevateprivileges=allow,spawn=allow,resourcecontrol=deny -readconfig /run/incus/ha/qemu.conf -spice unix=on,disable-ticketing=on,addr=/run/incus/ha/qemu.spice -pidfile /run/incus/ha/qemu.pid -D /var/log/incus/ha/qemu.log -smbios type=2,manufacturer=LinuxContainers,product=Incus -runas incus: : exit status 1
Try `incus info --show-log ha` for more info
```

```
user@incsrv3:/run/incus$ incus info --show-log ha
Name: ha
Description: 
Status: STOPPED
Type: virtual-machine
Architecture: x86_64
Created: 2024/11/06 21:32 GMT
Last Used: 2025/02/24 21:34 GMT

Log:

qemu-system-x86_64: Address space limit 0xfffffffff < 0x107fffffff phys-bits too low (36)
```

```
user@incsrv3:/run/incus$ lscpu                                                            
Architecture:             x86_64                                                           
  CPU op-mode(s):         32-bit, 64-bit                                                   
  Address sizes:          36 bits physical, 48 bits virtual 
```

I welcome any advice on this.

**Comment by stgraber** [comment]
Can you show `cat /run/incus/ha/qemu.conf` as well as `incus config show --expanded ha`?

**Comment by clendee** [comment]
qemu.conf

```
# Machine
[machine]
graphics = "off"
type = "q35"
accel = "kvm"
usb = "off"

[global]
driver = "ICH9-LPC"
property = "disable_s3"
value = "1"

[global]
driver = "ICH9-LPC"
property = "disable_s4"
value = "0"

[boot-opts]
strict = "on"

# Memory
[memory]
size = "2048M"
slots = "16"
maxmem = "15506M"

# CPU
[smp-opts]
cpus = "1"
maxcpus = "4"

[object "mem0"]
qom-type = "memory-backend-memfd"
size = "2048M"
share = "on"

[numa]
type = "node"
nodeid = "0"
memdev = "mem0"

# Firmware (read only)
[drive]
file = "/opt/incus/share/qemu/OVMF_CODE.4MB.fd"
if = "pflash"
format = "raw"
unit = "0"
readonly = "on"

# Firmware settings (writable)
[drive]
file = "/dev/fd/4"
if = "pflash"
format = "raw"
unit = "1"

# Qemu control
[chardev "monitor"]
backend = "socket"
path = "/run/incus/ha/qemu.monitor"
server = "on"
wait = "off"

[mon]
chardev = "monitor"
mode = "control"

# Console
[chardev "console"]
backend = "ringbuf"
size = "1048576"

# VM core info driver
[device "qemu_vmcoreinfo"]
driver = "vmcoreinfo"

[device "qemu_pcie0"]
driver = "pcie-root-port"
bus = "pcie.0"
addr = "1.0"
chassis = "0"
multifunction = "on"

# Balloon driver
[device "qemu_balloon"]
driver = "virtio-balloon-pci"
bus = "qemu_pcie0"
addr = "00.0"
multifunction = "on"

# Random number generator
[object "qemu_rng"]
qom-type = "rng-random"
filename = "/dev/urandom"

[device "dev-qemu_rng"]
driver = "virtio-rng-pci"
bus = "qemu_pcie0"
addr = "00.1"
rng = "qemu_rng"

# Input
[device "qemu_keyboard"]
driver = "virtio-keyboard-pci"
bus = "qemu_pcie0"
addr = "00.2"

# Input
[device "qemu_tablet"]
driver = "virtio-tablet-pci"
bus = "qemu_pcie0"
addr = "00.3"

# Vsock
[device "qemu_vsock"]
driver = "vhost-vsock-pci"
bus = "qemu_pcie0"
addr = "00.4"
guest-cid = "266977020"
vhostfd = "3"

# Virtual serial bus
[device "dev-qemu_serial"]
driver = "virtio-serial-pci"
bus = "qemu_pcie0"
addr = "00.5"

# Serial identifier
[chardev "qemu_serial-chardev"]
backend = "ringbuf"
size = "16B"

[device "qemu_serial"]
driver = "virtserialport"
name = "org.linuxcontainers.incus"
chardev = "qemu_serial-chardev"
bus = "dev-qemu_serial.0"

[device "qemu_serial_legacy"]
driver = "virtserialport"
name = "org.linuxcontainers.lxd"
bus = "dev-qemu_serial.0"

# Spice agent
[chardev "qemu_spice-chardev"]
backend = "spicevmc"
name = "vdagent"

[device "qemu_spice"]
driver = "virtserialport"
name = "com.redhat.spice.0"
chardev = "qemu_spice-chardev"
bus = "dev-qemu_serial.0"

# Spice folder
[chardev "qemu_spicedir-chardev"]
backend = "spiceport"
name = "org.spice-space.webdav.0"

[device "qemu_spicedir"]
driver = "virtserialport"
name = "org.spice-space.webdav.0"
chardev = "qemu_spicedir-chardev"
bus = "dev-qemu_serial.0"

# USB controller
[device "qemu_usb"]
driver = "qemu-xhci"
bus = "qemu_pcie0"
addr = "00.6"
p2 = "8"
p3 = "8"

[chardev "qemu_spice-usb-chardev1"]
backend = "spicevmc"
name = "usbredir"

[device "qemu_spice-usb1"]
driver = "usb-redir"
chardev = "qemu_spice-usb-chardev1"

[chardev "qemu_spice-usb-chardev2"]
backend = "spicevmc"
name = "usbredir"

[device "qemu_spice-usb2"]
driver = "usb-redir"
chardev = "qemu_spice-usb-chardev2"

[chardev "qemu_spice-usb-chardev3"]
backend = "spicevmc"
name = "usbredir"

[device "qemu_spice-usb3"]
driver = "usb-redir"
chardev = "qemu_spice-usb-chardev3"

[device "qemu_pcie1"]
driver = "pcie-root-port"
bus = "pcie.0"
addr = "1.1"
chassis = "1"

# SCSI controller
[device "qemu_scsi"]
driver = "virtio-scsi-pci"
bus = "qemu_pcie1"
addr = "00.0"

[device "qemu_pcie2"]
driver = "pcie-root-port"
bus = "pcie.0"
addr = "1.2"
chassis = "2"

# Shared config drive (9p)
[fsdev "qemu_config"]
fsdriver = "local"
security_model = "none"
readonly = "on"
path = "/var/lib/incus/devices/ha/config.mount"

[device "dev-qemu_config-drive-9p"]
driver = "virtio-9p-pci"
bus = "qemu_pcie2"
addr = "00.0"
multifunction = "on"
mount_tag = "config"
fsdev = "qemu_config"

# Shared agent drive (9p)
[fsdev "qemu_agent"]
fsdriver = "local"
security_model = "none"
readonly = "on"
path = "/opt/incus/agent/"

[device "dev-qemu_agent-drive-9p"]
driver = "virtio-9p-pci"
bus = "qemu_pcie2"
addr = "00.1"
mount_tag = "agent"
fsdev = "qemu_agent"

[device "qemu_pcie3"]
driver = "pcie-root-port"
bus = "pcie.0"
addr = "1.3"
chassis = "3"

# GPU
[device "qemu_gpu"]
driver = "virtio-vga"
bus = "qemu_pcie3"
addr = "00.0"

[device "qemu_pcie4"]
driver = "pcie-root-port"
bus = "pcie.0"
addr = "1.4"
chassis = "4"

# VM Generation ID
[device "vmgenid0"]
driver = "vmgenid"
guid = "b18afd29-194e-4d2a-ac26-d5f0a59ff691"

[device "qemu_pcie5"]
driver = "pcie-root-port"
bus = "pcie.0"
addr = "1.5"
chassis = "5"

[device "qemu_pcie6"]
driver = "pcie-root-port"
bus = "pcie.0"
addr = "1.6"
chassis = "6"

[device "qemu_pcie7"]
driver = "pcie-root-port"
bus = "pcie.0"
addr = "1.7"
chassis = "7"

[device "qemu_pcie8"]
driver = "pcie-root-port"
bus = "pcie.0"
addr = "2.0"
chassis = "8"
multifunction = "on"

[device "qemu_pcie9"]
driver = "pcie-root-port"
bus = "pcie.0"
addr = "2.1"
chassis = "9"

[device "qemu_pcie10"]
driver = "pcie-root-port"
bus = "pcie.0"
addr = "2.2"
chassis = "10"

[device "qemu_pcie11"]
driver = "pcie-root-port"
bus = "pcie.0"
addr = "2.3"
chassis = "11"

[device "qemu_pcie12"]
driver = "pcie-root-port"
bus = "pcie.0"
addr = "2.4"
chassis = "12"
```

expanded ha

```
architecture: x86_64
config:
  boot.autostart: "true"
  image.architecture: amd64
  image.description: Debian bullseye amd64 (20230628_05:25)
  image.os: Debian
  image.release: bullseye
  image.serial: "20230628_05:25"
  image.type: disk-kvm.img
  image.variant: default
  limits.cpu: "2"
  limits.memory: 2GiB
  volatile.base_image: 612c1c66a9a77088efa82be4b4b0cfc94aa81f46fc9a38c2e71f2cbcd24ed191
  volatile.cloud-init.instance-id: 5305ff1f-1118-4199-8bbd-9885aa7065e0
  volatile.eth0.hwaddr: 00:16:3e:40:ff:12
  volatile.last_state.power: RUNNING
  volatile.uuid: b18afd29-194e-4d2a-ac26-d5f0a59ff691
  volatile.uuid.generation: b18afd29-194e-4d2a-ac26-d5f0a59ff691
  volatile.vsock_id: "266977020"
devices:
  bluetooth:
    productid: "8771"
    type: usb
    vendorid: 0bda
  bluetoothUSB:
    productid: "8771"
    type: usb
    vendorid: 0bda
  eth0:
    nictype: macvlan
    parent: br0
    type: nic
    vlan: "91"
  root:
    path: /
    pool: default
    size: 15GiB
    type: disk
ephemeral: false
profiles:
- vlan91
stateful: false
description: ""

```
